#########################################################
# YNode - Site configuration file
#
# This configuration file sets up the environment variables related to the site
# While these could be set in ynode.conf, they're separated for clarity
# Launch `server.sh --conf /path/to/ynode.conf --conf /path/to/site.conf` 
# Some of these options can also be set on the command line
# Refer to server.sh or launch `./server.sh --help` for more details
#
#########################################################

# The directory where the default error pages live.
# It should contain something like "404.html" "500.html"...
export YN_DEFAULT_PAGES_DIR=$(realpath "./default_pages")

# The document root for the website, used as the base to resolve request paths
# Relative paths are supported but are not recommended
export YN_HTTP_ROOT=$(realpath -- ./www-demo/)

